version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password

  # main rails blob
  ruby:
    build: .
    command: bundle exec rails s --pid /tmp/server.pid
    volumes:
      - .:/myapp
    ports:
      - 5000:5000
    links:
      - postgres
      - webpack
    environment:
      DATABASE_URL: postgres
    depends_on:
      - postgres
      - webpack

  # Runs the webpack dev server, because foreman goes away.
  webpack:
    build: .
    volumes:
      - .:/myapp
    command: ./bin/webpack-dev-server
    ports:
      - 3035:3035

# Make a volume, because windows screws up the the permissions
# so postgres has a fit.
volumes:
  postgres:
    driver: local
